export const metadata = {
  title: "Selfie",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Global styles */}
        <style>{`
          body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: #f0f0f0;
          }
          header {
            background: #fff;
            padding: 1rem 2rem;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            display: flex;
            align-items: center;
          }
          header img {
            height: 50px;
            margin-right: 1rem;
          }
          main {
            max-width: 960px;
            margin: 2rem auto;
            background: #fff;
            padding: 2rem;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          footer {
            text-align: center;
            padding: 1rem;
            font-size: 0.9rem;
            color: #777;
          }
        `}</style>
      </head>
      <body>
        <header>
          <h1>{metadata.title}</h1>
        </header>
        <main>{children}</main>
        <footer>
          Organize your Future Self <br />
          Made in NextJS V15.2.1 <br />
          {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}
